logs:
  files:
    directory: ./logs
    enabled: true
    keepFor: 30
  level: info
presence:
  activities:
    - name: /new
    - name: with {totalTickets} tickets
    - name: "{openTickets} tickets"
      type: 3
    - name: "{avgResponseTime} response time"
      type: 3
  interval: 20
  status: online
stats: true
templates:
  transcript: transcript.md
updates: true
